using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Logging.Abstractions;
using Yap.Services;

// Run from the repository root. Only shipped assets enter this public catalog;
// deployment-specific packs and account preferences still come from the protected API.
var root = Path.GetFullPath("Yap");
var temporary = Path.Combine(Path.GetTempPath(), "yap-emoji-catalog-" + Guid.NewGuid());
Directory.CreateDirectory(temporary);
try
{
    var env = new CatalogEnvironment { ContentRootPath = temporary, WebRootPath = Path.Combine(root, "wwwroot") };
    var custom = new CustomEmojiService(env, NullLogger<CustomEmojiService>.Instance);
    Directory.SetCurrentDirectory(root); // EmojiService scans shipped local overrides here.
    var emoji = new EmojiService(custom);
    string Source(string value) => Regex.Match(emoji.GetEmojiHtml(value).Value, "src=\"([^\"]+)\"").Groups[1].Value;
    var categories = custom.Packs.Select(p => new
    {
        key = p.Key,
        name = p.DisplayName,
        icon = p.Emojis[0].Url,
        items = p.Emojis.Select(e => new { value = $":{e.Shortcode}:", keywords = e.Keywords, src = e.Url }).ToArray()
    }).Concat(EmojiData.Categories.Select(c => new
    {
        key = c.Key,
        name = c.Key,
        icon = Source(c.Value.Icon),
        items = c.Value.Emojis.Select(e => new { value = e, keywords = EmojiData.EmojiKeywords.GetValueOrDefault(e) ?? "", src = Source(e) }).ToArray()
    })).ToArray();
    var folder = Path.Combine(env.WebRootPath, "chat-client", "emoji");
    var keys = Directory.GetFiles(folder, "*.svg").Select(Path.GetFileNameWithoutExtension).Order(StringComparer.Ordinal).ToArray();
    var options = new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };
    File.WriteAllText(Path.Combine(folder, "catalog.js"),
        "// Generated by scripts/EmojiCatalog. Metadata only; artwork loads individually.\nexport const categories = " +
        JsonSerializer.Serialize(categories, options) + ";\nexport const artworkKeys = " +
        JsonSerializer.Serialize(keys, options) + ";\n");
    Console.WriteLine($"Generated {categories.Sum(c => c.items.Length)} picker entries and {keys.Length} artwork filenames.");
}
finally
{
    Directory.Delete(temporary, true);
}

sealed class CatalogEnvironment : IWebHostEnvironment
{
    public string ApplicationName { get; set; } = "EmojiCatalog";
    public string EnvironmentName { get; set; } = "Development";
    public string ContentRootPath { get; set; } = "";
    public string WebRootPath { get; set; } = "";
    public IFileProvider ContentRootFileProvider { get; set; } = new NullFileProvider();
    public IFileProvider WebRootFileProvider { get; set; } = new NullFileProvider();
}
